title: 朱凯的个人主页
page-top-title: 朱凯
top-section-bg-text: 知识如水，求知若渴。
home-subtitle: <span class="english-name">Kai Zhu</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="chinese-name">朱凯</span>
awards-subtitle: <i class="bi bi-award-fill"></i>&nbsp;奖项
experience-subtitle: <i class="bi bi-briefcase-fill"></i>&nbsp;研究经历
publications-subtitle: <i class="bi bi-file-text-fill"></i>&nbsp;论文发表
copyright-text: '&copy; 朱凯 2023-2025。版权所有。'
