title: Kai Zhu's Homepage
page-top-title: Kai Zhu
top-section-bg-text: Seeking knowledge, writ in water.
home-subtitle: <span class="english-name">Kai Zhu</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="chinese-name">朱凯</span>
copyright-text: '&copy; Kai Zhu 2023-2025. All Rights Reserved.'
